### ISSUE TITLE
Deprecation: opIn_r is deprecated.

### ISSUE THREAD

**Issue by andre2007** [MartinNowak/hyphenate#2]
https://github.com/MartinNowak/hyphenate/blob/4ea5883d85d7d56396d6d0ddbf84a308834fc238/src/hyphenate.d#L128

I get this deprecation, not sure why it shows another line number:
/home/user/.dub/packages/hyphenate-1.1.2/hyphenate/src/hyphenate.d(280,26): Deprecation: opIn_r is deprecated.  Use opBinaryRight(string op)(...) if (op == "in") instead.

**Comment by ibuclaw** [comment]
opIn is pending removal.

https://github.com/dlang/dmd/pull/12902
